# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lections.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lections.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elections.proto\x12\x08lections\"$\n\x0eLectionRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\"\xbb\x02\n\x11LectionAttendance\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nstudent_id\x18\x02 \x01(\x05\x12\x19\n\x11student_full_name\x18\x03 \x01(\t\x12\x12\n\nfaculty_id\x18\x04 \x01(\x05\x12\x14\n\x0c\x66\x61\x63ulty_name\x18\x05 \x01(\t\x12\x10\n\x08group_id\x18\x06 \x01(\x05\x12\x12\n\ngroup_name\x18\x07 \x01(\t\x12\x12\n\nlection_id\x18\x08 \x01(\x05\x12\x12\n\nsubject_id\x18\t \x01(\x05\x12\x14\n\x0csubject_name\x18\n \x01(\t\x12\x12\n\nteacher_id\x18\x0b \x01(\x05\x12\x19\n\x11teacher_full_name\x18\x0c \x01(\t\x12\x17\n\x0fstart_timestamp\x18\r \x01(\t\x12\x15\n\rend_timestamp\x18\x0e \x01(\t2d\n\x0fLectionsService\x12Q\n\x14GetLectionAttendance\x12\x18.lections.LectionRequest\x1a\x1b.lections.LectionAttendance\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lections_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LECTIONREQUEST']._serialized_start=28
  _globals['_LECTIONREQUEST']._serialized_end=64
  _globals['_LECTIONATTENDANCE']._serialized_start=67
  _globals['_LECTIONATTENDANCE']._serialized_end=382
  _globals['_LECTIONSSERVICE']._serialized_start=384
  _globals['_LECTIONSSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
